import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex">
        <SidebarProvider defaultOpen={true} open={true}>
          <AppSidebar />
          <main className=" flex-1 p-4">
            <SidebarTrigger className=" md:hidden" />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
